### ISSUE TITLE
Using server as systemd service returns Unhandled exception

### ISSUE THREAD

**Issue by 0marduk** [Nova-Atomic/Rimworld-Together#1]
Hello,
When setting up my server I wanted to create a systemd service for the server, this is how it looks:
```
[Unit]
Description=Rimworld Server Service
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
User=root
ExecStart=/bin/dotnet /home/www/rserver/GameServer.dll
WorkingDirectory=/home/www/rserver/
[Install]
WantedBy=multi-user.target
```
However, when attempting to launch, I receive this error.
```
Jul 19 18:15:36 hostname dotnet[1538]: Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
Jul 19 18:15:36 hostname dotnet[1538]:    at GameServer.ServerCommandManager.ParseServerCommands(String parsedString)
Jul 19 18:15:36 hostname dotnet[1538]:    at GameServer.ServerCommandManager.ListenForServerCommands()
Jul 19 18:15:36 hostname dotnet[1538]:    at GameServer.Program.Main()
```

Am I by any chance doing something wrong?

**Comment by 0marduk** [comment]
Very well, is there an option to disable input?

**Comment by Nova-Atomic** [comment]
> Very well, is there an option to disable input?

Not right now, but I'll make sure to refer this issue to the one in charge of the server functions in this moment.

**Comment by Nova-Atomic** [comment]
Closing as it will be fixed in next release
